<a href="https://colab.research.google.com/github/AbzalovAR/Programming_and_Artificial_Intelligence/blob/main/Titanic_Analitics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
import pandas as pd # базовая классическая библиотека для анализа данных
import matplotlib.pyplot as plt # для графического изображения данных
import seaborn as sns # так же для графического отображения, но строит более красивые графики
import plotly.express as px #
%matplotlib inline

In [17]:
data=pd.read_csv('/content/9_Titanic_Dataset.xls')

In [18]:
# Просматриваем первые десять строк из набора данных
data.head(n=10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [19]:
# Посмотрим общую информацию о датасете
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


Как видим датафрейм состоит из 12 столбцов.
Типы данных соответсвуют содержимому столбца, разве что столбец Age можно привести к типу int64, раз уж возраст прописан целыми числами.
Мы видим что имеются пропущенные значения в столбцах Age, Cabin, Embarked.

In [20]:
# Посморим сколько пропущенных значений в столбцах
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Столбец Age дозаполним медианным значением возраста.

Столбец Embarked - имеет только 2 пропущенных значения - эти строки удалим - 2 строки не существенны для датасета, а чем заполнить пропуски не известно.

Столбец Cabin напрашивается на удаление, но уже сам столбец. Так как слишком большой % отсутствующих значений может вредить анализу, а дозаполнить данные не представляется возможным.

In [21]:
data['Age'] = data['Age'].fillna(data['Age'].median())

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [23]:
# Посмотрим уникальные значения возраста и поймем есть ли необходимость в типе данных float
data['Age'].unique()

array([22.  , 38.  , 26.  , 35.  , 28.  , 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  ,  8.  ,
       19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  , 49.  ,
       29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  , 16.  ,
       25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  , 71.  ,
       37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 , 51.  ,
       55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  , 45.5 ,
       20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  , 60.  ,
       10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  , 70.  ,
       24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

Есть значения 0,83 и 0,92, 0,75 - это либо ошибки где перед возрастом случайно попал нолик, либо возраст младецев, в отличие от других пассажиров на корабле записали как десятичное значение. Сомневаюсь про младецев, но попробую проверить - выведу строки с возрастом меньше 1 года:

In [24]:
data.query('Age < 1')

PassengerId  Survived  Pclass                             Name     Sex  \
78            79         1       2    Caldwell, Master. Alden Gates    male   
305          306         1       1   Allison, Master. Hudson Trevor    male   
469          470         1       3    Baclini, Miss. Helene Barbara  female   
644          645         1       3           Baclini, Miss. Eugenie  female   
755          756         1       2        Hamalainen, Master. Viljo    male   
803          804         1       3  Thomas, Master. Assad Alexander    male   
831          832         1       2  Richards, Master. George Sibley    male   

      Age  SibSp  Parch  Ticket      Fare    Cabin Embarked  
78   0.83      0      2  248738   29.0000      NaN        S  
305  0.92      1      2  113781  151.5500  C22 C26        S  
469  0.75      2      1    2666   19.2583      NaN        C  
644  0.75      2      1    2666   19.2583      NaN        C  
755  0.67      1      1  250649   14.5000      NaN        S  
803  0.42      0      1    2625    8.5167      NaN        C  
831  0.83      1      1   29106   18.7500      NaN        S

Проверил через интернет имена - это действительно были младецы. Значит ошибки нет возраст записан верно.

Удалим строки с пустым значением Embarked:

In [25]:
# Посмотрим уникальные значения столбца
data['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [26]:
# Удалим пустые строки
data = data.dropna(subset=['Embarked'])

Теперь удалим лишние столбцы

In [27]:
# Удалим ненужные столбцы - PassengerId тоже не несет смысла для решения нашей задачи
data.drop(['PassengerId', 'Cabin', 'Name'],axis = 1,inplace = True) # inplace = True - означает перезаписать переменную data

In [28]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  889 non-null    int64  
 1   Pclass    889 non-null    int64  
 2   Sex       889 non-null    object 
 3   Age       889 non-null    float64
 4   SibSp     889 non-null    int64  
 5   Parch     889 non-null    int64  
 6   Ticket    889 non-null    object 
 7   Fare      889 non-null    float64
 8   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 69.5+ KB


Переводим все строки в категории

In [29]:
from sklearn.preprocessing import LabelEncoder

labelsToEncode=['Sex','Ticket','Embarked']
for label in labelsToEncode:
  le = LabelEncoder()
  data[label] = le.fit_transform(data[label])

После того как мы перевели все строчне значения в категории - мы можем проверить корреляцию:

In [30]:
px.imshow(data.corr(),title="Корреляционная матрица")

Никакой явной корреляции не видно. Нас больше всего интересует столбец Survived.

In [31]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch  Ticket     Fare  Embarked
0         0       3    1  22.0      1      0     522   7.2500         2
1         1       1    0  38.0      1      0     595  71.2833         0
2         1       3    0  26.0      0      0     668   7.9250         2
3         1       1    0  35.0      1      0      48  53.1000         2
4         0       3    1  35.0      0      0     471   8.0500         2

Одним из этапов предворительной обработки данных является стандартизация значений, она используется, когда значения в большом диапазоне, для упращение тренировки модели диапазон значений уменьшается

In [32]:
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report,confusion_matrix


In [33]:
scaler = StandardScaler()
# Нормализация числовых признаков, кроме нашего целевого признака
scaler.fit(data.drop(['Survived'],axis=1))
scaler_features = scaler.transform(data.drop(['Survived'],axis=1))

In [34]:
scaler_features[0]

array([ 0.82520863,  0.73534203, -0.56367407,  0.43135024, -0.47432585,
        0.91701764, -0.50023975,  0.58683958])

Перед тренировкой модели датасет разбивается на 2 части, на тренировочный и на тестовый датасеты. Это делается для того, что бы после окончания тренировки модели проверить ее точность на данных, которая модель не видела

In [35]:
from sklearn.model_selection import train_test_split
# X = scaler_features
X = data.drop(['Survived'],axis=1)
Y = data['Survived']
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.3,random_state=4)

Ниже предоставленны несколько моделей и их метрики, для определения точности модели использовались следующие метрики


1.   Среднеквадратичная ошибка
2.   Среднеквадратичная ошибка в процентах

Линейная регрессия

In [36]:
# Среднее арифметическое  квадратов разностей между предсказанными и реальными значениями:
from sklearn.metrics import mean_squared_error

# относительная ошибка, где разность между наблюдаемым и фактическим значениями делится на наблюдаемое значение и выражается в процентах:
from sklearn.metrics import mean_absolute_percentage_error

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LassoCV

In [37]:
reg=LinearRegression()
reg.fit(X_train,Y_train)

LinearRegression()

In [38]:
pred = reg.predict(X_test)

In [39]:
X_test

Pclass  Sex   Age  SibSp  Parch  Ticket     Fare  Embarked
858       3    0  24.0      0      3     193  19.2583         0
291       1    0  19.0      1      0      63  91.0792         0
263       1    1  40.0      0      0      16   0.0000         2
322       2    0  30.0      0      0     123  12.3500         1
820       1    0  52.0      1      1      66  93.5000         2
..      ...  ...   ...    ...    ...     ...      ...       ...
615       2    0  24.0      1      2     105  65.0000         2
296       3    1  23.5      0      0     211   7.2292         0
657       3    0  32.0      1      1     434  15.5000         1
813       3    0   6.0      4      2     332  31.2750         2
536       1    1  45.0      0      0      21  26.5500         2

[267 rows x 8 columns]

In [40]:
pred

array([ 7.17963458e-01,  1.09545147e+00,  3.78482990e-01,  8.15839587e-01,
        7.70552364e-01,  4.51984865e-01,  1.42013462e-01,  4.45390450e-01,
        9.47741417e-02, -2.13161166e-01,  1.16054863e-01,  1.05210618e+00,
        1.54022045e-01,  9.29613449e-02,  6.42840022e-01,  6.65981253e-01,
        9.38074193e-02,  8.47728820e-02,  1.03834921e+00,  8.31301145e-03,
        2.92315618e-01, -3.06254345e-02,  8.45761571e-01,  1.72499986e-01,
        3.60823423e-02,  8.65100583e-02,  5.59528965e-01,  6.45120521e-01,
        6.37604737e-01,  4.15481694e-02,  2.94515046e-01, -2.14841861e-02,
        1.94494825e-01,  4.51973329e-01,  5.59054919e-01,  3.84241946e-01,
        4.81371374e-01, -1.23966476e-01,  1.06473688e+00,  5.24517590e-01,
        2.00169196e-01, -1.91706911e-01,  6.71684000e-01,  3.27317038e-01,
        5.32630747e-01,  5.83645128e-01,  1.18760561e-01,  9.66234416e-01,
        1.20159179e-01,  2.17808598e-01,  5.03485685e-01,  7.64722260e-02,
        1.18845156e-01,  

In [41]:
Y_test

858    1
291    1
263    0
322    1
820    1
      ..
615    1
296    0
657    0
813    0
536    0
Name: Survived, Length: 267, dtype: int64

In [42]:
mean_squared_error(Y_test, pred)

0.14981770538995737

In [43]:
mean_absolute_percentage_error(Y_test, pred)

671701022791413.2

ЧТО это означает? Невероятно огромный процент не точности!

Случайный лес

In [44]:
regr = RandomForestRegressor(max_depth=4, random_state=4)
regr.fit(X_train, Y_train)

RandomForestRegressor(max_depth=4, random_state=4)

In [45]:
pred2 = regr.predict(X_test)

In [46]:
mean_squared_error(Y_test, pred2)

0.12697670000433

In [47]:
mean_absolute_percentage_error(Y_test, pred2)

574600334130180.1

In [48]:
lassoReg = LassoCV(cv=5, random_state=0).fit(X_train, Y_train)

In [49]:
pred3 = lassoReg.predict(X_test)

In [50]:
mean_squared_error(Y_test, pred3)

0.15021190198601228

In [51]:
mean_absolute_percentage_error(Y_test, pred3)

701568611908901.6